ronyforms/routes/web.php
<?php

namespace App\Http\Controllers;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|  commande : php artisan route: list
*/

// Laravel Auth, credits to : https://www.itsolutionstuff.com/post/laravel-custom-login-and-registration-exampleexample.html

Route::get('login', [AuthController::class, 'index'])->name('login');
Route::post('post-login', [AuthController::class, 'postLogin'])->name('login.post'); 
Route::get('registration', [AuthController::class, 'registration'])->name('register');
Route::post('post-registration', [AuthController::class, 'postRegistration'])->name('register.post'); 
Route::get('dashboard', [AuthController::class, 'dashboard']); 
Route::get('logout', [AuthController::class, 'logout'])->name('logout');

Route::get('/', 'HomeController@home')->name('home');

// Formilaire routes
Route::resource('formulaires', 'FormulaireController');

// Section routes
Route::get('sections/create/{formulaire_id}/', 'SectionController@create_with_form_id')->name('sections.create_with_form_id');
Route::post('sections/store/{formulaire_id}/', 'SectionController@store_with_form_id')->name('sections.store_with_form_id');
Route::resource('sections', 'SectionController');

// SousSection routes
Route::get('sous_sections/create/{section_id}/', 'SousSectionController@create_with_section_id')->name('sous_sections.create_with_section_id');
Route::post('sous_sections/store/{section_id}/', 'SousSectionController@store_with_section_id')->name('sous_sections.store_with_section_id');
Route::resource('sous_sections', 'SousSectionController');

// Widget routes
Route::get('widgets/create/{sous_section_id}/', 'WidgetController@create_with_sous_section_id')->name('widgets.create_with_sous_section_id');
Route::post('widgets/store/{sous_section_id}/', 'WidgetController@store_with_sous_section_id')->name('widgets.store_with_sous_section_id');
Route::resource('widgets', 'WidgetController');

// ReponseCourte routes
Route::get('reponse_courtes/create/{widget_id}/', 'ReponseCourteController@create_with_widget_id')->name('reponse_courtes.create_with_widget_id');
Route::post('reponse_courtes/store/{widget_id}/', 'ReponseCourteController@store_with_widget_id')->name('reponse_courtes.store_with_widget_id');
Route::resource('reponse_courtes', 'ReponseCourteController');

// Paragraphe routes
Route::get('paragraphes/create/{widget_id}/', 'ParagrapheController@create_with_widget_id')->name('paragraphes.create_with_widget_id');
Route::post('paragraphes/store/{widget_id}/', 'ParagrapheController@store_with_widget_id')->name('paragraphes.store_with_widget_id');
Route::resource('paragraphes', 'ParagrapheController');

// ChoixMultiple routes
Route::get('choix_multiples/create/{widget_id}/', 'ChoixMultipleController@create_with_widget_id')->name('choix_multiples.create_with_widget_id');
Route::post('choix_multiples/store/{widget_id}/', 'ChoixMultipleController@store_with_widget_id')->name('choix_multiples.store_with_widget_id');
Route::resource('choix_multiples', 'ChoixMultipleController');

// EchelleLineaire routes
Route::get('echelle_lineaires/create/{widget_id}/', 'EchelleLineaireController@create_with_widget_id')->name('echelle_lineaires.create_with_widget_id');
Route::post('echelle_lineaires/store/{widget_id}/', 'EchelleLineaireController@store_with_widget_id')->name('echelle_lineaires.store_with_widget_id');
Route::resource('echelle_lineaires', 'EchelleLineaireController');

// ListeDiroulante routes
Route::get('liste_diroulantes/create/{widget_id}/', 'ListeDiroulanteController@create_with_widget_id')->name('liste_diroulantes.create_with_widget_id');
Route::post('liste_diroulantes/store/{widget_id}/', 'ListeDiroulanteController@store_with_widget_id')->name('liste_diroulantes.store_with_widget_id');
Route::resource('liste_diroulantes', 'ListeDiroulanteController');

// CasesAcoche routes
Route::get('cases_acochers/create/{widget_id}/', 'CasesAcocherController@create_with_widget_id')->name('cases_acochers.create_with_widget_id');
Route::post('cases_acochers/store/{widget_id}/', 'CasesAcocherController@store_with_widget_id')->name('cases_acochers.store_with_widget_id');
Route::resource('cases_acochers', 'CasesAcocherController');

// DateHeure routes
Route::get('date_heures/create/{widget_id}/', 'DateHeureController@create_with_widget_id')->name('date_heures.create_with_widget_id');
Route::post('date_heures/store/{widget_id}/', 'DateHeureController@store_with_widget_id')->name('date_heures.store_with_widget_id');
Route::resource('date_heures', 'DateHeureController');

// Reponse routes
Route::get('reponses/create/{widget_id}/', 'ReponseController@create_with_widget_id')->name('reponses.create_with_widget_id');
Route::post('reponses/store/{widget_id}/', 'ReponseController@store_with_widget_id')->name('reponses.store_with_widget_id');
Route::resource('reponses', 'ReponseController');

ronyforms/app/Models/Paragraphe.php
<?php
// php artisan make:model Paragraphe -m
namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Paragraphe extends Model
{
    use HasFactory;

    protected $fillable = ['contenu'];

    // ManyToOne
    public function widget(){
        return $this->belongsTo(Widget::class);
    }
}

ronyforms/app/Http/Controllers/ParagrapheController.php
<?php
// commande : php artisan make:controller ParagrapheController --resource
namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Paragraphe;

class ParagrapheController extends Controller
{
    public function create_with_widget_id($widget_id)
    {
        return view('paragraphe/create', 
                    ['widget_id' => $widget_id]
                );
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $paragraphes = Paragraphe::all();
        
        return view('paragraphe/index',compact('paragraphes'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('paragraphe/create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store_with_widget_id(Request $request, $widget_id)
    {
        $validatedData = $request->validate([
                    'contenu' => 'required|max:100'
                ]);
        $show = new Paragraphe($validatedData);
        $show->widget_id = $widget_id;
        $show->save();
        
        return redirect('/paragraphes')->with('success', 'Paragraphe is successfully saved');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $user = Auth::user();

        $validatedData = $request->validate([
            'contenu' => 'required|max:100'
        ]);
        $show = new Paragraphe($validatedData);
        $show->user_id = $user->id;
        $show->section_id = 1;
        $show->save();
        
        return redirect('/paragraphes')->with('success', 'Paragraphe is successfully saved');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $paragraphe = Paragraphe::findOrFail($id);
        return view('paragraphe/show',compact('paragraphe'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $paragraphe = Paragraphe::findOrFail($id);

        return view('paragraphe/edit', compact('paragraphe'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validatedData = $request->validate([
            'contenu' => 'required|max:100'
        ]);
        Paragraphe::whereId($id)->update($validatedData);

        return redirect('/paragraphes')->with('success', 'Paragraphe Data is successfully updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $paragraphe = Paragraphe::findOrFail($id);
        $paragraphe->delete();

        return redirect('/paragraphes')->with('success', 'Paragraphe Data is successfully deleted');
    }
}

ronyforms/resources/views/paragraphe/create.blade.php
@extends('layout')

@section('title', 'Home')

@section('content')
<main class="login-form">
  <div class="cotainer">
      <div class="row justify-content-center">
          <div class="col-md-8">
              <div class="card">
                  <div class="card-header">Veuillez renseigner les informations du paragraphe</div>
                  <div class="card-body">

                    @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div><br />
                    @endif

                    <form action="{{ route('paragraphes.store_with_widget_id', $widget_id) }}" method="POST">
                          @csrf
                          <div class="form-group row">
                              <label for="contenu" class="col-md-4 col-form-label text-md-right">Contenu</label>
                              <div class="col-md-6">
                                  <input type="text" id="contenu" class="form-control" name="contenu" required autofocus>
                              </div>
                          </div>
  
                          <div class="col-md-6 offset-md-4">
                              <button type="submit" class="btn btn-primary">
                                  Ajouter
                              </button>
                          </div>
                    </form>
                        
                  </div>
              </div>
          </div>
      </div>
  </div>
</main>
@endsection

ronyforms/resources/views/paragraphe/edit.blade.php
@extends('layout')

@section('title', 'Home')

@section('content')
<main class="login-form">
  <div class="cotainer">
      <div class="row justify-content-center">
          <div class="col-md-8">
              <div class="card">
                  <div class="card-header">Veuillez renseigner les informations du paragraphe</div>
                  <div class="card-body">
  
                      <form action="{{ route('paragraphes.update', $paragraphe->id) }}" method="POST">
                          @csrf
                          @method('PUT')
                          
                          <div class="form-group row">
                              <label for="contenu" class="col-md-4 col-form-label text-md-right">Contenu</label>
                              <div class="col-md-6">
                                  <input type="text" id="contenu" class="form-control" value="{{ $paragraphe->contenu }}" name="contenu" required autofocus>
                              </div>
                          </div>

                          <div class="col-md-6 offset-md-4">
                              <button type="submit" class="btn btn-primary">
                                  Submitter
                              </button>
                          </div>
                      </form>
                        
                  </div>
              </div>
          </div>
      </div>
  </div>
</main>
@endsection

ronyforms/resources/views/paragraphe/index.blade.php
@extends('layout')

@section('title', 'Home')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Liste des paragraphes') }}</div>
  
                <div class="card-body">
                    @if(session()->get('success'))
                        <div class="alert alert-success">
                        {{ session()->get('success') }}  
                        </div><br />
                    @endif
                    <ol>
                        @foreach($paragraphes as $paragraphe)
                            <a href="{{ route('paragraphes.show', $paragraphe->id) }}"><li>  <strong>{{ $paragraphe->contenu }} :</strong></a>
                           
                            <br> Added at {{  $paragraphe->created_at->diffForHumans() }}
                            <br>
                        @endforeach
                    </ol>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

ronyforms/resources/views/paragraphe/show.blade.php
@extends('layout')

@section('title', 'Details Formulaire')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Details Paragraphe') }}</div>
  
                <div class="card-body">
                    <a href="{{ route('paragraphes.edit', $paragraphe->id) }}">Edit</a>
                        <form action="{{ route('paragraphes.destroy', $paragraphe->id) }}" method="POST">
                            @csrf
                            @method('DELETE')
            
                            <button type="submit" class="btn btn-danger">Delete</button>
                        </form>
                    <li>  
                        <strong>{{ $paragraphe->contenu }} :</strong> 
                    </li>
                        <br> Added at {{  $paragraphe->created_at->diffForHumans() }}
                </div>
            </div>
        </div>
    </div>
</div>   
    

@endsection