ronyforms/routes/web.php
<?php

namespace App\Http\Controllers;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|  commande : php artisan route: list
*/

// Laravel Auth, credits to : https://www.itsolutionstuff.com/post/laravel-custom-login-and-registration-exampleexample.html

Route::get('login', [AuthController::class, 'index'])->name('login');
Route::post('post-login', [AuthController::class, 'postLogin'])->name('login.post'); 
Route::get('registration', [AuthController::class, 'registration'])->name('register');
Route::post('post-registration', [AuthController::class, 'postRegistration'])->name('register.post'); 
Route::get('dashboard', [AuthController::class, 'dashboard']); 
Route::get('logout', [AuthController::class, 'logout'])->name('logout');

Route::get('/', 'HomeController@home')->name('home');

// Formilaire routes
Route::resource('formulaires', 'FormulaireController');

// Section routes
Route::get('sections/create/{formulaire_id}/', 'SectionController@create_with_form_id')->name('sections.create_with_form_id');
Route::post('sections/store/{formulaire_id}/', 'SectionController@store_with_form_id')->name('sections.store_with_form_id');
Route::resource('sections', 'SectionController');

// SousSection routes
Route::get('sous_sections/create/{section_id}/', 'SousSectionController@create_with_section_id')->name('sous_sections.create_with_section_id');
Route::post('sous_sections/store/{section_id}/', 'SousSectionController@store_with_section_id')->name('sous_sections.store_with_section_id');
Route::resource('sous_sections', 'SousSectionController');

// Widget routes
Route::get('widgets/create/{sous_section_id}/', 'WidgetController@create_with_sous_section_id')->name('widgets.create_with_sous_section_id');
Route::post('widgets/store/{sous_section_id}/', 'WidgetController@store_with_sous_section_id')->name('widgets.store_with_sous_section_id');
Route::resource('widgets', 'WidgetController');

// ReponseCourte routes
Route::get('reponse_courtes/create/{widget_id}/', 'ReponseCourteController@create_with_widget_id')->name('reponse_courtes.create_with_widget_id');
Route::post('reponse_courtes/store/{widget_id}/', 'ReponseCourteController@store_with_widget_id')->name('reponse_courtes.store_with_widget_id');
Route::resource('reponse_courtes', 'ReponseCourteController');

// Paragraphe routes
Route::get('paragraphes/create/{widget_id}/', 'ParagrapheController@create_with_widget_id')->name('paragraphes.create_with_widget_id');
Route::post('paragraphes/store/{widget_id}/', 'ParagrapheController@store_with_widget_id')->name('paragraphes.store_with_widget_id');
Route::resource('paragraphes', 'ParagrapheController');

// ChoixMultiple routes
Route::get('choix_multiples/create/{widget_id}/', 'ChoixMultipleController@create_with_widget_id')->name('choix_multiples.create_with_widget_id');
Route::post('choix_multiples/store/{widget_id}/', 'ChoixMultipleController@store_with_widget_id')->name('choix_multiples.store_with_widget_id');
Route::resource('choix_multiples', 'ChoixMultipleController');

// EchelleLineaire routes
Route::get('echelle_lineaires/create/{widget_id}/', 'EchelleLineaireController@create_with_widget_id')->name('echelle_lineaires.create_with_widget_id');
Route::post('echelle_lineaires/store/{widget_id}/', 'EchelleLineaireController@store_with_widget_id')->name('echelle_lineaires.store_with_widget_id');
Route::resource('echelle_lineaires', 'EchelleLineaireController');

// ListeDiroulante routes
Route::get('liste_diroulantes/create/{widget_id}/', 'ListeDiroulanteController@create_with_widget_id')->name('liste_diroulantes.create_with_widget_id');
Route::post('liste_diroulantes/store/{widget_id}/', 'ListeDiroulanteController@store_with_widget_id')->name('liste_diroulantes.store_with_widget_id');
Route::resource('liste_diroulantes', 'ListeDiroulanteController');

// CasesAcoche routes
Route::get('cases_acochers/create/{widget_id}/', 'CasesAcocherController@create_with_widget_id')->name('cases_acochers.create_with_widget_id');
Route::post('cases_acochers/store/{widget_id}/', 'CasesAcocherController@store_with_widget_id')->name('cases_acochers.store_with_widget_id');
Route::resource('cases_acochers', 'CasesAcocherController');

// DateHeure routes
Route::get('date_heures/create/{widget_id}/', 'DateHeureController@create_with_widget_id')->name('date_heures.create_with_widget_id');
Route::post('date_heures/store/{widget_id}/', 'DateHeureController@store_with_widget_id')->name('date_heures.store_with_widget_id');
Route::resource('date_heures', 'DateHeureController');

// Reponse routes
Route::get('reponses/create/{widget_id}/', 'ReponseController@create_with_widget_id')->name('reponses.create_with_widget_id');
Route::post('reponses/store/{widget_id}/', 'ReponseController@store_with_widget_id')->name('reponses.store_with_widget_id');
Route::resource('reponses', 'ReponseController');

ronyforms/app/Models/Formulaire.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Formulaire extends Model
{
    use HasFactory;

    protected $fillable = ['titre', 'cadre', 'description'];

    public function sections(){
        return $this->hasMany(Section::class);
    }
}

ronyforms/app/Http/Controllers/FormulaireController.php
<?php
// commande : php artisan make:controller FormulaireController --resource
// tuto : https://appdividend.com/2020/10/13/laravel-8-crud-tutorial-example-step-by-step-from-scratch/

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Formulaire;
use Illuminate\Support\Facades\Auth;

class FormulaireController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $formulaires = Formulaire::all();
        
        return view('formulaire/index',compact('formulaires'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('formulaire/create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $user = Auth::user();

        $validatedData = $request->validate([
                    'titre' => 'required|max:255',
                    'cadre' => 'required',
                    'description' => 'required'
                ]);

        $show = new Formulaire($validatedData);
        $show->save(); 

        $lier = new Lier($validatedData);
        $lier->user_id = $user->id;
        $lier->formulaire_id = $formulaire->id;
        $lier->save(); 
        
        
        return redirect('/formulaires')->with('success', 'Formulaire is successfully saved');
        
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $formulaire = Formulaire::findOrFail($id);
        return view('formulaire/show',compact('formulaire'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $formulaire = Formulaire::findOrFail($id);

        return view('formulaire/edit', compact('formulaire'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validatedData = $request->validate([
            'titre' => 'required|max:255',
            'cadre' => 'required',
            'description' => 'required'
        ]);
        Formulaire::whereId($id)->update($validatedData);

        return redirect('/formulaires')->with('success', 'Formulaire Data is successfully updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $formulaire = Formulaire::findOrFail($id);
        $formulaire->delete();

        return redirect('/formulaires')->with('success', 'Formulaire Data is successfully deleted');
    }
}

ronyforms/resources/views/formulaire/create.blade.php
@extends('layout')

@section('title', 'Home')

@section('content')
<main class="login-form">
  <div class="cotainer">
      <div class="row justify-content-center">
          <div class="col-md-8">
              <div class="card">
                  <div class="card-header">Veuillez renseigner les informations du formulaire</div>
                  <div class="card-body">

                    @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div><br />
                    @endif

                    <form action="{{ route('formulaires.store') }}" method="POST">
                          @csrf
                          <div class="form-group row">
                              <label for="titre" class="col-md-4 col-form-label text-md-right">Titre</label>
                              <div class="col-md-6">
                                  <input type="text" id="titre" class="form-control" name="titre" required autofocus>
                              </div>
                          </div>
  
                          <div class="form-group row">
                              <label for="cadre" class="col-md-4 col-form-label text-md-right">Cadre</label>
                              <div class="col-md-6">
                                  <input type="cadre" id="cadre" class="form-control" name="cadre">
                              </div>
                          </div>

                          <div class="form-group row">
                              <label for="description" class="col-md-4 col-form-label text-md-right">Description</label>
                              <div class="col-md-6">
                                  <input type="description" id="description" class="form-control" name="description">
                              </div>
                          </div>
  
                          <div class="col-md-6 offset-md-4">
                              <button type="submit" class="btn btn-primary">
                                  Ajouter
                              </button>
                          </div>
                    </form>
                        
                  </div>
              </div>
          </div>
      </div>
  </div>
</main>
@endsection

ronyforms/resources/views/formulaire/edit.blade.php
@extends('layout')

@section('title', 'Home')

@section('content')
<main class="login-form">
  <div class="cotainer">
      <div class="row justify-content-center">
          <div class="col-md-8">
              <div class="card">
                  <div class="card-header">Veuillez renseigner les informations du formulaire</div>
                  <div class="card-body">
  
                      <form action="{{ route('formulaires.update', $formulaire->id) }}" method="POST">
                          @csrf
                          @method('PUT')
                          
                          <div class="form-group row">
                              <label for="titre" class="col-md-4 col-form-label text-md-right">Titre</label>
                              <div class="col-md-6">
                                  <input type="text" id="titre" class="form-control" value="{{ $formulaire->titre }}" name="titre" required autofocus>
                              </div>
                          </div>
  
                          <div class="form-group row">
                              <label for="cadre" class="col-md-4 col-form-label text-md-right">Cadre</label>
                              <div class="col-md-6">
                                  <input type="cadre" id="cadre" class="form-control" value="{{ $formulaire->cadre }}" name="cadre" required>
                              </div>
                          </div>

                          <div class="form-group row">
                              <label for="description" class="col-md-4 col-form-label text-md-right">Description</label>
                              <div class="col-md-6">
                                  <input type="description" id="description" class="form-control" value="{{ $formulaire->description }}" name="description" required>
                              </div>
                          </div>
  
                          <div class="col-md-6 offset-md-4">
                              <button type="submit" class="btn btn-primary">
                                  Submitter
                              </button>
                          </div>
                      </form>
                        
                  </div>
              </div>
          </div>
      </div>
  </div>
</main>
@endsection

ronyforms/resources/views/formulaire/index.blade.php
@extends('layout')

@section('title', 'Home')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Liste des Formulaires') }}</div>
  
                <div class="card-body">
                    @if(session()->get('success'))
                        <div class="alert alert-success">
                        {{ session()->get('success') }}  
                        </div><br />
                    @endif
                    <ol>
                        @foreach($formulaires as $formulaire)
                            <a href="{{ route('formulaires.show',$formulaire->id) }}"><li>  <strong>{{ $formulaire->titre }} :</strong></a>
                            {{ $formulaire->cadre }} </li>
                            <p>{{ $formulaire->description }}</p>
                            <br> Added at {{  $formulaire->created_at->diffForHumans() }}
                            <br>
                        @endforeach
                    </ol>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

ronyforms/resources/views/formulaire/show.blade.php
@extends('layout')

@section('title', 'Details Formulaire')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Details Formulaire') }}</div>
  
                <div class="card-body">
                    <li>  
                        <strong>{{ $formulaire->titre }} :</strong>  {{ $formulaire->cadre }} 
                    </li>
                        <a href="{{ route('formulaires.edit', $formulaire->id) }}">Edit</a>
                        <form action="{{ route('formulaires.destroy', $formulaire->id) }}" method="POST">
                            @csrf
                            @method('DELETE')
            
                            <button type="submit" class="btn btn-danger">Delete</button>
                        </form>
                        <p>{{ $formulaire->description }} </p>
                        <!--<br> Added at {{  $formulaire->created_at->diffForHumans() }}-->
                        @foreach($formulaire->sections as $section)
                            <fieldset class="sec_fieldset">
                                <legend>{{ $section->titre }}</legend>
                                <p>{{ $section->description }} </p>
                                <!--Added at {{  $section->created_at->diffForHumans() }}-->
                                @foreach($section->sous_sections as $sous_section)
                                    <fieldset class="ssec_fieldset">
                                        <legend>{{ $sous_section->titre }}</legend>
                                        <p>{{ $sous_section->description }} </p>
                                        <!--Added at {{  $sous_section->created_at->diffForHumans() }}-->
                                        @foreach($sous_section->widgets as $widget)
                                            <fieldset class="widget_fieldset">
                                                <!--<legend>{{ $widget->id }}</legend>-->
                                                <!--<p>{{ $widget->user_id }} </p>-->
                                                <!--Added at {{  $widget->created_at->diffForHumans() }}-->
                                                <fieldset>
                                                    @foreach($widget->choix_multiples as $choix_multiple)
                                                        <label>{{ $choix_multiple->contenu }} : </label>
                                                        <input type="radio" name="{{ $choix_multiple->contenu }}" id="{{ $choix_multiple->contenu }}">
                                                    @endforeach
                                                    @foreach($widget->cases_acochers as $cases_acocher)
                                                        <label>{{ $cases_acocher->contenu }} : </label>
                                                        <input type="checkbox" name="{{ $cases_acocher->contenu }}" id="{{ $cases_acocher->contenu }}">
                                                    @endforeach
                                                    @foreach($widget->date_heures as $date_heure)
                                                        <label>{{ $date_heure->valeur }} : </label>
                                                        <input type="datetime-local" name="{{ $date_heure->valeur }}" id="{{ $date_heure->valeur }}">
                                                    @endforeach
                                                    @foreach($widget->liste_diroulantes as $liste_diroulante)
                                                        <label>{{ $liste_diroulante->contenu }} :</label>
                                                        <select id="types_widget" name="type_widget_id">
                                                                <option value="test"> {{ $liste_diroulante->contenu }} </option>
                                                        </select>
                                                    @endforeach
                                                    @foreach($widget->reponse_courtes as $reponse_courte)
                                                        <label>{{ $reponse_courte->contenu }} :</label>
                                                        <input type="text" name="{{ $reponse_courte->contenu }}" id="{{ $reponse_courte->contenu }}">
                                                    @endforeach
                                                    @foreach($widget->paragraphes as $paragraphe)
                                                        <label for="{{ $paragraphe->contenu }}">{{ $paragraphe->contenu }} :</label>
                                                        <textarea id="{{ $paragraphe->contenu }}" name="{{ $paragraphe->contenu }}">
                                                                It was a dark and stormy night...
                                                        </textarea>
                                                    @endforeach
                                                    @foreach($widget->echelle_lineaires as $echelle_lineaire)
                                                        <label>{{ $echelle_lineaire->contenu }} :</label>
                                                        <input type="range" list="tickmarks">
                                                    @endforeach
                                                </fieldset>
                                            </fieldset>
                                        @endforeach
                                        <a href="{{ route('widgets.create_with_sous_section_id', $sous_section->id) }}">+ Widget</a>
                                    </fieldset>
                                @endforeach
                                <a href="{{ route('sous_sections.create_with_section_id', $section->id) }}">+ SousSection</a>
                            </fieldset>
                        @endforeach
                        <a href="{{ route('sections.create_with_form_id', $formulaire->id) }}">+ Section</a>
                        

                </div>
            </div>
        </div>
    </div>
</div>   
    

@endsection